version: '3.8'

services:

  backend:
    build: .
    container_name: backend
    volumes:
      - backend_data:/app/
      - staticfiles:/app/static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
        
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - staticfiles:/app/static/
    ports:
      - "80:80"
    depends_on:
      - backend
  
  db:
    image: postgres
    container_name: psqldb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello

volumes:
  backend_data:
    name: backend_data
    driver: local
    driver_opts:
      device: ./backend
      o: bind
      type: none
  
  staticfiles:
      name: staticfiles
      driver: local
      driver_opts:
        device: ./static
        o: bind
        type: none

  postgres_data:
    name: postgres_data

networks:
  default:
    name: main_network