version: '3.8'

services:
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - django_data:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: psqldb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  django_data:
    name: django_data
    driver: local
    driver_opts:
      device: ./
      o: bind
      type: none
  
  postgres_data:
    name: postgres_data
    # driver: local
    # driver_opts:
    #   device: ./postgres
    #   o: bind
    #   type: none

networks:
  default:
    name: main_network
