# Generated by Django 5.0.4 on 2024-05-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='win_loss_margin',
            field=models.JSONField(default=list),
        ),
    ]
