# Generated by Django 5.0.6 on 2024-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_player_win_loss_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
