# Generated by Django 5.0.4 on 2024-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamerequest_gameschedule_tournament_tournamentlobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequest',
            name='game_id',
            field=models.IntegerField(choices=[(0, 'Pong'), (1, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='game_mode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='game_id',
            field=models.IntegerField(choices=[(0, 'Pong'), (1, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='game_mode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
